### ISSUE TITLE
corpus.NewEnglishCorpus fails when GOPATH has multiple components

### ISSUE THREAD

**Issue by robert-uhl** [AntoineAugusti/wordsegmentation#1]
It simply appends `"/src/github.com/antoineaugusti/wordsegmentation/data/"` to the GOPATH, which doesn't work when GOPATH is of the form `/usr/local/share/go:/home/me/go:/home/projects/foo`.

**Comment by robert-uhl** [comment]
Here's a solution: https://github.com/AntoineAugusti/wordsegmentation/pull/2

**Comment by AntoineAugusti** [comment]
Fixed in https://github.com/AntoineAugusti/wordsegmentation/pull/2
